- hosts: all
  vars:
    - source_dir: /home/genomics/software/.source
    - software_dir: /home/genomics/software
    - workshop_dir: /home/genomics/workshop_materials
    
  pre_tasks:
      # Create genomics user Software Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory owner=genomics
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory owner=genomics
    - name: Create Workshop Directory
      file: path={{workshop_dir}} state=directory owner=genomics
      
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create genomics Workshop User
      user: name=genomics comment="Genomics Workshop User" password='$6$xsb/UrhJ$sxievieZ7erTF93MwiBEZqm/mIpTVlTd3uhYGY2Urt5qoGapG3ZEU6NrGMOYd7QUnFfXhgDn12OPxDuxb20dB0'
    
    - name: Installing Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
       - libhdf5-cpp-11 #blasr
       - libhdf5-dev #blasr
      
  tasks:
    # Installing Commonly Required Programs 
    - name: Installing bamtools
      apt: name={{item}} state=present
      with_items:
       - bamtools
       - libbamtools-dev
       - libbamtools2.4.0
   
    ### Introduction to Unix ###
    ## Get Julian's materials from ???
    
    ### Sequence Data Quality Control ###
    ## Data
    #Get data from Sophie/Josie
    
    ## Software
    # Cutadapt
    - name: Installing cutadapt
      pip: name=cutadapt state=present
  
    # Seqtk
    - name: Cloning seqtk
      git: repo=https://github.com/lh3/seqtk.git dest="{{source_dir}}/seqtk" clone=yes update=yes
    - name: Building/Installing seqtk
      shell: "{{item}}"
      args:
       chdir: "{{source_dir}}/seqtk" 
      with_items:
        - make
        - cp seqtk /usr/local/bin
  
    # Install other required programs, luckily all in debian science repo
    - name: Install ea-utils 1.04.676, trimmomatic, fastqc 0.11.4
      apt: name={{item}} state=present
      with_items:
       - ea-utils
       - trimmomatic
       - fastqc

    # Install Trim Galore!
    - include: trim_galore.yaml

    ### Alignment Methods ###
    ## Data
    
    ### Genomics ###
    ## Previously Installed Above 
    # FastQC, fastq-mcf
    ## Data
    ## Software
