- hosts: all
  vars:
    - source_dir: /home/genomics/software/.source
    - software_dir: /home/genomics/software
    
  pre_tasks:
      # Create genomics user Software Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory owner=genomics
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory owner=genomics
      
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create genomics Workshop User
      user: name=genomics comment="Genomics Workshop User" password='$6$xsb/UrhJ$sxievieZ7erTF93MwiBEZqm/mIpTVlTd3uhYGY2Urt5qoGapG3ZEU6NrGMOYd7QUnFfXhgDn12OPxDuxb20dB0'
    
    - name: Installing Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
      
  tasks:
    # Installing Commonly Required Programs 
    - name: Installing bamtools
      apt: name={{item}} state=present
      with_items:
       - bamtools
       - libbamtools-dev
       - libbamtools2.4.0
   
    ### Introduction to Unix
    ## Get Julian's materials from ???
    
    ### Sequence Data Quality Control
    ## Data
    #Get data from Sophie/Josie
    
    ## Software
    # Cutadapt
    - name: Installing cutadapt
      pip: name=cutadapt state=present
  
    # Seqtk
    - name: Cloning seqtk
      git: repo=https://github.com/lh3/seqtk.git dest="{{source_dir}}/seqtk" clone=yes update=yes
    - name: Building/Installing seqtk
      shell: "{{item}}"
      args:
       chdir: "{{source_dir}}/seqtk" 
      with_items:
        - make
        - cp seqtk /usr/local/bin
  
    # EA Utils (fastq-mcf)
    # requires: libgsl0-dev, libsparsehash-dev, bamtools
    #- name: Cloning EA Utils
    #  git: repo=https://github.com/ExpressionAnalysis/ea-utils.git dest="{{source_dir}}/ea-utils" clone=yes update=yes force=yes
    #- name: Building/Installing ea-utils
    #  shell: "{{item}}"
    #  args:
    #   chdir: "{{source_dir}}/ea-utils/clipper"
    #  with_items:
    #   - make
    #   - make install
    
    # Install other required programs, luckily all in debian science repo
    - name: Install ea-utils 1.04.676, trimmomatic, fastqc 0.11.4
      apt: name={{item}} state=present
      with_items:
       - ea-utils
       - trimmomatic
       - fastqc

    # Install Trim Galore!
    - include: trim_galore.yaml
