- hosts: all
  vars:
    - source_dir: /home/genomics/software/.source
    - software_dir: /home/genomics/software
    - workshop_dir: /home/genomics/workshop_materials
    
  pre_tasks:
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create genomics Workshop User
      user: name=genomics group=workshop comment="Genomics Workshop User" state=present shell=/bin/bash password='$6$xsb/UrhJ$sxievieZ7erTF93MwiBEZqm/mIpTVlTd3uhYGY2Urt5qoGapG3ZEU6NrGMOYd7QUnFfXhgDn12OPxDuxb20dB0'
      
    # Create genomics user Software Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory owner=genomics
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory owner=genomics
    - name: Create Workshop Directory
      file: path={{workshop_dir}} state=directory owner=genomics
      
    - name: Installing Some Other Build Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
       - libhdf5-cpp-11 #blasr
       - libhdf5-dev #blasr
      
  tasks:
    ### Commonly Required Programs ###
    - name: Installing bamtools
      apt: name={{item}} state=present
      with_items:
       - bamtools
       - libbamtools-dev
       - libbamtools2.4.0
       - sra-toolkit

    - name: Installing BioPerl - slow
      cpanm: name=CJFIELDS/BioPerl-1.6.924.tar.gz
      tags: bioperl

    - name: Installing BioPython
      pip: name=biopython state=present
      tags: biopython
   
    ### Introduction to Unix ###
    ## Get Julian's materials from ???
    

    ### Sequence Data Quality Control ###
    ## Data
    #Get data from Sophie/Josie
    
    ## Software
    - include: seqtk.yaml
      tags: seqtk
      
    - include: trim_galore.yaml version=0.4.1
      tags: trim_galore
    
    - name: Installing cutadapt
      pip: name=cutadapt state=present
      tags: cutadapt

    - name: Install ea-utils 1.04.676, trimmomatic, fastqc 0.11.4
      apt: name={{item}} state=present
      with_items:
       - ea-utils
       - trimmomatic
       - fastqc


    ### Alignment Methods ###
    ## Data
    ## Software
    # This requires > 4GB memory to install, what to do!
    #- include: blasr.yaml
    #  tags: blasr


    ### Genomics ###
    ## Previously Installed
    # FastQC, fastq-mcf, seqtk, blasr

    ## Data
    ## Software
    - include: bwa.yaml
      tags: bwa
      
    - include: samtools.yaml version=1.3.1
      tags: samtools
    - include: bcftools.yaml version=1.3.1
      tags: bcftools
      
    - name: Installing blast legacy & blast+
      apt: name={{item}} state=present
      with_items:
       - ncbi-blast+
       - ncbi-blast+-legacy
       - ncbi-tools-bin
       - ncbi-tools-x11
      tags: blast
      
    - name: Installing EMBOSS tools (getorf)
      apt: name={{item}} state=present
      with_items:
       - emboss
       - emboss-data
       - emboss-doc
       - emboss-lib
       - jemboss
      tags: emboss
      
    - name: Installing FastTree2
      apt: name=fasttree state=present
      tags: fasttree
    - name: Install FastTree2 Links
      file: src=/usr/bin/fasttree dest=/usr/bin/FastTree state=link
      tags: fasttree
    - name: Install FastTree2 Links
      file: src=/usr/bin/fasttreeMP dest=/usr/bin/FastTreeMP state=link
      tags: fasttree
      
    - include: igv.yaml version=2.3.80
      tags: igv
    - include: igvtools.yaml version=2.3.80
      tags: igvtools
      
    - name: Install bedtools
      apt: name=bedtools state=present
      tags: bedtools

    - include: qualimap.yaml version=2.2
      tags: qualimap

    - include: SPAdes.yaml version=3.9.0
      tags: spades

    - include: quast.yaml version=4.2
      tags: quast

    - include: hmmer.yaml version=3.1b2
      tags: hmmer

    - name: Installing Velvet Assembler
      apt: name={{item}} state=present
      with_items:
       - velvet
       - velvet-example
      tags: velvet

    - include: bam2fastq.yaml version=1.1.0
      tags: bam2fastq

    - include: newick_utils.yaml
      tags: newick_utils

    - include: picard_tools.yaml
      tags: picard_tools

    - include: genomics_tutorial_extras.yaml
      tags: genomics_extras


    ### Genome Assembly ###
    ## Previously Installed
    # velvet, SPAdes, QUAST

    ## Data
    ## Software
    - include: minia.yaml version=2.0.7
      tags: minia

    - include: kmergenie.yaml version=1.7016
      tags: kmergenie
