- hosts: all
  vars:
    - source_dir: /home/genomics/software/.source
    - software_dir: /home/genomics/software
    - workshop_dir: /home/genomics/workshop_materials
    
  pre_tasks:
      # Create genomics user Software Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory owner=genomics
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory owner=genomics
    - name: Create Workshop Directory
      file: path={{workshop_dir}} state=directory owner=genomics
      
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create genomics Workshop User
      user: name=genomics comment="Genomics Workshop User" password='$6$xsb/UrhJ$sxievieZ7erTF93MwiBEZqm/mIpTVlTd3uhYGY2Urt5qoGapG3ZEU6NrGMOYd7QUnFfXhgDn12OPxDuxb20dB0'
    
    - name: Installing Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
       - libhdf5-cpp-11 #blasr
       - libhdf5-dev #blasr
      
  tasks:
    # Installing Commonly Required Programs 
    - name: Installing bamtools
      apt: name={{item}} state=present
      with_items:
       - bamtools
       - libbamtools-dev
       - libbamtools2.4.0
   
    ### Introduction to Unix ###
    ## Get Julian's materials from ???
    
    ### Sequence Data Quality Control ###
    ## Data
    #Get data from Sophie/Josie
    
    ## Software
    - include: seqtk.yaml
      tags: seqtk
    - include: trim_galore.yaml
      tags: trim_galore
    
    - name: Installing cutadapt
      pip: name=cutadapt state=present
      tags: cutadapt

    - name: Install ea-utils 1.04.676, trimmomatic, fastqc 0.11.4
      apt: name={{item}} state=present
      with_items:
       - ea-utils
       - trimmomatic
       - fastqc

    ### Alignment Methods ###
    ## Data
    ## Software
    #- include: blasr.yaml tags=blasr
    
    ### Genomics ###
    ## Previously Installed Above 
    # FastQC, fastq-mcf
    ## Data
    ## Software
    - include: bwa.yaml
      tags: bwa
    - include: samtools.yaml
      tags: samtools
    - include: bcftools.yaml
      tags: bcftools
    - name: Installing blast legacy & blast+
      apt: name={{item}} state=present
      with_items:
       - ncbi-blast+
       - ncbi-blast+-legacy
       - ncbi-tools-bin
       - ncbi-tools-x11
      tags: blast
    - name: Installing EMBOSS tools (getorf)
      apt: name={{item}} state=present
      with_items:
       - emboss
       - emboss-data
       - emboss-doc
       - emboss-lib
       - jemboss
      tags: emboss
    - name: Installing FastTree2
      apt: name={{item}} state=present
      with_items:
       - fasttree
      tags: fasttree
    - name: Install FastTree2 Links
      file: src=/usr/bin/fasttree dest=/usr/bin/FastTree state=link
      tags: fasttree
    - name: Install FastTree2 Links
      file: src=/usr/bin/fasttreeMP dest=/usr/bin/FastTreeMP state=link
      tags: fasttree
    - include: igv.yaml
      tags: igv
