- hosts: all
  vars:
    - source_dir: /home/ubuntu/software/.source
    - software_dir: /home/ubuntu/software
    
  pre_tasks:
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create genomics Workshop User
      user: name=genomics comment="Genomics Workshop User" password='$6$xsb/UrhJ$sxievieZ7erTF93MwiBEZqm/mIpTVlTd3uhYGY2Urt5qoGapG3ZEU6NrGMOYd7QUnFfXhgDn12OPxDuxb20dB0'
    
    - name: Installing Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
      
  tasks: 
    ### Introduction to Unix
    ## Get Julian's materials from ???
    
    ### Sequence Data Quality Control
    ## Data
    #Get data from Sophie/Josie
    
    ## Software
    # Cutadapt
    - name: Installing cutadapt
      pip: name=cutadapt state=present
  
    # Seqtk
    - name: Cloning seqtk
      git: repo=https://github.com/lh3/seqtk.git dest="{{source_dir}}/seqtk" clone=yes update=yes
    - name: Building/Installing seqtk
      shell: "{{item}}"
      args:
       chdir: "{{source_dir}}/seqtk" 
      with_items:
        - make
        - cp seqtk /usr/local/bin
  
    # EA Utils (fastq-mcf)
    # requires: libgsl0-dev, libsparsehash-dev
    - name: Cloning EA Utils
      git: repo=https://github.com/ExpressionAnalysis/ea-utils.git dest="{{source_dir}}/ea-utils" clone=yes update=yes force=yes
    - name: Building/Installing ea-utils
      shell: "{{item}}"
      args:
       chdir: "{{source_dir}}/ea-utils/clipper"
      with_items:
       - make
       - make install
