- hosts: all
  become: yes
  vars:
    - workshop_user: genomics
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - software_dir: "/home/{{workshop_user}}/software"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"

  tasks:
  ### Common ###


  ### Unix ###
  - name: Create Unix Directory
    file: path="{{workshop_dir}}/unix" state=directory owner="{{workshop_user}}" group=workshop
    tags: unix

  - name: Downloading Unix Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/unix.tar.gz"
      dest="{{source_dir}}/unix.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: unix

  - name: Uncompressing Unix Dataset
    unarchive:
      src="{{source_dir}}/unix.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/unix/contigs.fa.gz"
    tags: unix



  ### Sequencing Data + Quality Control ###
  - name: Create QC Directory
    file: path="{{workshop_dir}}/quality_control" state=directory owner="{{workshop_user}}" group=workshop
    tags: quality

  - name: Downloading Quality Control Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/quality_control.tar.gz"
      dest="{{source_dir}}/quality_control.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: quality

  - name: Uncompressing Quality Control Dataset
    unarchive:
      src="{{source_dir}}/quality_control.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/quality_control/adaptors.fasta"
    tags: quality



  ### Alignment Methods ###
  - name: Create Alignment Methods Directory
    file: path="{{workshop_dir}}/alignment_methods" state=directory owner="{{workshop_user}}" group=workshop
    tags: alignment

  - name: Downloading Alignment Methods Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/alignment_methods.tar.gz"
      dest="{{source_dir}}/alignment_methods.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: alignment

  - name: Uncompressing Alignment Methods Dataset
    unarchive:
      src="{{source_dir}}/alignment_methods.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/alignment_methods/PB.fasta"
    tags: alignment



  ### Genomics ###
  - name: Create Genomics Tutorial Directory
    file: path="{{workshop_dir}}/genomics_tutorial" state=directory owner="{{workshop_user}}" group=workshop
    tags: genomics

  - name: Downloading Genomics Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/genomics_tutorial.tar.gz"
      dest="{{source_dir}}/genomics_tutorial.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: genomics

  - name: Uncompressing R Tutorial Dataset
    unarchive:
      src="{{source_dir}}/genomics_tutorial.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/qiime/genomics_tutorial/"
    tags: genomics



  ### Assembly ###
  - name: Create Assembly Directory
    file: path="{{workshop_dir}}/assembly" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### Introduction to R ###
  - name: Create R Tutorial Directory
    file: path="{{workshop_dir}}/R_tutorial" state=directory owner="{{workshop_user}}" group=workshop
    tags: R

  - name: Downloading R Tutorial Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/R_tutorial.tar.gz"
      dest="{{source_dir}}/R_tutorial.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: R

  - name: Uncompressing R Tutorial Dataset
    unarchive:
      src="{{source_dir}}/R_tutorial.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/R_tutorial/healthy_metadata.txt"
    tags: R



  ### QIIME ###
  - name: Create QIIME Directory
    file: path="{{workshop_dir}}/qiime" state=directory owner="{{workshop_user}}" group=workshop
    tags: qiime

  - name: Downloading QIIME Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/qiime.tar.gz"
      dest="{{source_dir}}/qiime.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: qiime

  - name: Uncompressing R Tutorial Dataset
    unarchive:
      src="{{source_dir}}/qiime.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/qiime/illumina_overview_tutorial.ipynb"
    tags: qiime



  ### PhyloSeq ###
  - name: Create Phyloseq Directory
    file: path="{{workshop_dir}}/phyloseq" state=directory owner="{{workshop_user}}" group=workshop
    tags: phyloseq


  ### Rad-Seq / Stacks ###
  - name: Create Rad-Seq Directory
    file: path="{{workshop_dir}}/radseq" state=directory owner="{{workshop_user}}" group=workshop
    tags: radseq, stacks


  ### Transcriptomics ###

  - name: Create Transcriptomics Directory
    file: path="{{workshop_dir}}/transcriptomics" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics

  - name: Create Trinotate databases Directory
    file: path="{{workshop_dir}}/transcriptomics/trinotate_databases" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics

  - include: data_tasks/swissprot.yaml
    tags: transcriptomics, swissprot

  - include: data_tasks/pfam.yaml
    tags: transcriptomics, pfam

  - include: data_tasks/trinotate.yaml
    tags: transcriptomics, trinotate

  - name: Cloning Trinity Workshop
    git: repo=https://github.com/trinityrnaseq/KrumlovTrinityWorkshopJan2016.git dest="{{workshop_dir}}/transcriptomics/KrumlovTrinityWorkshopJan2016" clone=yes update=yes
