- hosts: all
  become: yes
  vars:
    - workshop_user: genomics
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - software_dir: "/home/{{workshop_user}}/software"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"

  tasks:
  ### Common ###


  ### Unix ###
  - name: Create Unix Directory
    file: path="{{workshop_dir}}/unix" state=directory owner="{{workshop_user}}" group=workshop
    tags: unix


  ### Sequencing Data + Quality Control ###
  - name: Create QC Directory
    file: path="{{workshop_dir}}/quality_control" state=directory owner="{{workshop_user}}" group=workshop
    tags: quality

  - name: Downloading Quality Control Dataset
    get_url:
      url="https://s3.amazonaws.com/2017evomics/quality_control.tar.gz"
      dest="{{source_dir}}/quality_control.tar.gz"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 5
    delay: 10
    tags: quality

  - name: Uncompressing Quality Control Dataset
    unarchive:
      src="{{source_dir}}/qulaity_control.tar.gz"
      dest="{{workshop_dir}}"
      copy=no
      creates="{{workshop_dir}}/quality_control/adaptors.fasta"
    tags: quality


  ### Alignment Methods ###
  - name: Create Alignment Methods Directory
    file: path="{{workshop_dir}}/alignment_methods" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### Genomics ###
  - name: Create Genomics Tutorial Directory
    file: path="{{workshop_dir}}/genomics_tutorial" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### Assembly ###
  - name: Create Assembly Directory
    file: path="{{workshop_dir}}/assembly" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### Introduction to R ###
  - name: Create R Tutorial Directory
    file: path="{{workshop_dir}}/R_tutorial" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### QIIME ###
  - name: Create QIIME Directory
    file: path="{{workshop_dir}}/qiime" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### PhyloSeq ###
  - name: Create Phyloseq Directory
    file: path="{{workshop_dir}}/phyloseq" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### Rad-Seq / Stacks ###
  - name: Create Rad-Seq Directory
    file: path="{{workshop_dir}}/radseq" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics


  ### Transcriptomics ###

  - name: Create Transcriptomics Directory
    file: path="{{workshop_dir}}/transcriptomics" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics

  - name: Create Trinotate databases Directory
    file: path="{{workshop_dir}}/transcriptomics/trinotate_databases" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics

  - include: data_tasks/swissprot.yaml
    tags: transcriptomics, swissprot

  - include: data_tasks/pfam.yaml
    tags: transcriptomics, pfam

  - include: data_tasks/trinotate.yaml
    tags: transcriptomics, trinotate
