- name: install MATE Desktop
  hosts: all
  pre_tasks:
    - name: check if overlay scrollbar is installed
      command: dpkg -s overlay-scrollbar
      register: overlay_scrollbar
      ignore_errors: true

    - name: disable scroll overlay
      command: gsettings set com.canonical.desktop.interface scrollbar-mode normal
      when: overlay_scrollbar.stdout.find('install ok installed') != -1

  tasks:
    - name: install mate desktop 
      apt:
        update_cache: yes
        name: mate-desktop-environment
        state: present
        cache_valid_time: 3600
      sudo: yes
   - name: install mate desktop extra
      apt:
        update_cache: yes
        name: mate-desktop-environment-extras
        state: present
        cache_valid_time: 3600
      sudo: yes
