- name: install MATE Desktop
  hosts: all
  pre_tasks:
    - name: disable scroll overlay
      command: apt-get purge overlay-scrollbar
      sudo: yes

  tasks:
    - name: install mate desktop 
      apt:
        update_cache: yes
        name: mate-desktop-environment
        state: present
        cache_valid_time: 3600
      sudo: yes

   - name: install mate desktop extra
      apt:
        update_cache: yes
        name: mate-desktop-environment-extras
        state: present
        cache_valid_time: 3600
      sudo: yes
